header light
anastasiiatarasiuk/TalentStack pull request #1
Opened 2024-06-12 13:51 UTC by NataliaShtefan

2024-06-12 18:54 UTC, anastasiiatarasiuk requested changes
Потрібно забрати клас heder з медіаправила для планшета, тому що стилі з нього не міняються та будуть наслідуватись .  Також у файлі не повинно бути порожніх медіазапитів. І потрібно доопрацювати стилі для мобільного меню

2024-06-13 11:05 UTC, NataliaShtefan commented
вже виправила

2024-06-13 12:28 UTC, anastasiiatarasiuk requested changes
Потрібно виправити стилі в мобільному меню

2024-06-13 13:54 UTC, anastasiiatarasiuk requested changes
Потрібно прибрати скролл сторінки у мобільному меню. Також потрібно щоб при зміні теми на темну в мобільному меню  змінювався колір svg на світлий, бо їх не видно. і коли після мобілки не вимикати темний режим, перемикач не працює коректно і не змінює колір сторінки назад

2024-06-13 18:39 UTC, anastasiiatarasiuk approved these changes

2024-06-13 18:39 UTC, merged