1st commit
anastasiiatarasiuk/TalentStack pull request #3
Opened 2024-06-13 14:34 UTC by RedisculuS

added css for white theme for 3 devices

2024-06-13 14:46 UTC, RedisculuS commented
ще нема темної теми та фонове зображення тримає з мене прикола

2024-06-13 15:22 UTC, anastasiiatarasiuk requested changes
Потрібно правильно завантажити фонові зображення, а також виправити стилі в списку соц мереж

2024-06-13 16:59 UTC, anastasiiatarasiuk requested changes
У медіаправилі для десктопа в класі social-list потрібно забрати width: 1280px;

2024-06-13 18:55 UTC, anastasiiatarasiuk requested changes
потрібно зробити фон списку з посиланнями по ширині сторінки

2024-06-14 19:41 UTC, anastasiiatarasiuk requested changes
Прибрати від'ємні маржини та змінити маржин для заголовку з 112px на 88px

2024-06-15 09:38 UTC, anastasiiatarasiuk requested changes
Для заголовка потрібно забрати margin-top. Але для класу hero-section потрібно поставити padding-top. у мобілки padding-top повинен бути 96px, для планшета 88px, для десктопа 168px. Це потрібно для того щоб background-image не виходив зя межі секції

2024-06-15 11:52 UTC, anastasiiatarasiuk requested changes
Потрібно додати в тег a  з класом order-project посилання на секцію work together -  href="#contacts"

2024-06-15 13:57 UTC, anastasiiatarasiuk requested changes
Потрібно видалити зайві фонові зображення

2024-06-15 14:11 UTC, anastasiiatarasiuk approved these changes

2024-06-15 14:11 UTC, merged