styles-commit-1
anastasiiatarasiuk/TalentStack pull request #4
Opened 2024-06-13 18:49 UTC by Qerilod

styles commit

2024-06-14 06:43 UTC, anastasiiatarasiuk requested changes
Потрібно зробити ховер і фокус  для посилань. Також потрібно додати фонове зображення. У класі .send-form  зайві min-width i height. Також для цього класу min-width не потрібен у медіаправилі для планшету. А на десктопі замінити його на width:100%. Для елемента textarea у його класі потрібно додати властивість resize: none, щоб заборонити користувачеві змінювати розмір. В заголовка секції, в абзаці та в посиланнях зайва властивість color.

2024-06-15 13:30 UTC, Qerilod commented
Я відправила виправлення до 1 коміту, в другому готовий Js, залишилась тільки модалка яка в процесі, та беграунд зображення

2024-06-15 17:54 UTC, anastasiiatarasiuk requested changes
Потрібно на останнє посилання в списку додати target:_blank; Також потрібно додати фонове зображення. Було б добре зберігати значення полів у локальне сховище. Також потрібно виправити стилі інпуту після введення даних.

2024-06-16 06:31 UTC, anastasiiatarasiuk requested changes
Фонове зображення потрібно додати через js

2024-06-17 11:59 UTC, anastasiiatarasiuk requested changes
Потрібно виправити позиціонування

2024-06-17 12:12 UTC, anastasiiatarasiuk requested changes
Потрібно додати модальне вікно при натисканні на кнопку

2024-06-17 16:20 UTC, anastasiiatarasiuk requested changes
Потрібно виправити код в pop-up.js щоб модальне вікно працювало коректно

2024-06-17 20:00 UTC, anastasiiatarasiuk requested changes
Потрібно видалити css клас backdrop і медіапрвило для мобілки для модального вікна

2024-06-17 20:04 UTC, anastasiiatarasiuk approved these changes

2024-06-17 20:04 UTC, merged